### ISSUE TITLE
The view is unexpectedly split

### ISSUE THREAD

**Issue by n826vnl8** [adrien-ben/gltf-viewer-rs#19] opened 2020-02-11 06:43 UTC
I tried this project a couple months ago, it works fine.

I dropped the code yesterday and I found Unexpected behavior is shown as below：

![split](https://user-images.githubusercontent.com/60425689/74215544-6046f300-4cdc-11ea-9261-19028c0bedc4.jpg)

**Comment by adrien-ben** [comment] 2020-02-11 07:23
Hi!

Indeed this is weird. Given the screenshot I think that broke when I added the post process step : 31704497f7b3aaefc022e0d88b15cf2c5e09aa6f

But I never had this issues on my test computers (windows 10 and linux). What platform are you running the code on ? 

Also, could you try these two commits just to make sure the problem is the post process step ? 

- before: 206802691a64b18b75d2eb0347e753d52b4e15f8
- after: 31704497f7b3aaefc022e0d88b15cf2c5e09aa6f

**Comment by n826vnl8** [comment] 2020-02-11 08:45
Thanks for your response and my environment is MacOS MoJave  10.14.6
I dropped the commit you mentioned and had a test. Below is result:
- 2068026   GOOD
- 3170449    BAD

**Comment by adrien-ben** [comment] 2020-02-11 11:35
Ok then it confirms what I thought, thank you, since I don't have access to any Mac I can't validate that I don't break anything on these platforms.

I could reproduce the issue on my computer by changing the post-process fragment shader code. But I don't really understand why it happens to you with the base shader code. I'm going to look at it a little bit more in depth during the week.

Well, this is project that I made to learn Vulkan and Rust. I come back to it when I have some time and ideas of things to implement. So, feel free to report any other issues, that's a goot way for me to learn things :)

**Comment by adrien-ben** [comment] 2020-02-11 11:50
I've tried something  : 5baabfe1d6b12640c7a426e62374e5be89f764d6

Could you check if it fixes the issue for you ? :)

**Comment by n826vnl8** [comment] 2020-02-11 19:19
Commit 5baabfe  really fixes this issue  👍

**Comment by adrien-ben** [comment] 2020-02-11 19:36
Cool ! It's been merged to master :)

**Closed** 2020-02-11 19:35 UTC
